spring:
  datasource:
    url: jdbc:mysql://devlog.cwmrubevoikp.us-east-1.rds.amazonaws.com:3306/devlog
    username: 
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  amazon:
    aws:
      accesskey:
      secretkey:
      sessiontoken:

      region: us-east-1  # e.g., us-east-1
      endpoint: https://dynamodb.us-east-1.amazonaws.com
      s3bucket-name: devlogresource
      s3Url: https://devlogresource.s3.amazonaws.com/
  security:
    oauth2:
      resource:
        userInfoUri: https://devlog.auth.us-east-1.amazoncognito.com/oauth2/userInfo
        tokenInfoUri: https://devlog.auth.us-east-1.amazoncognito.com/oauth2/token
        jwk:
          issuer-uri: https://cognito-idp.us-east-1.amazonaws.com/us-east-1_8r9aHJxHT
          key-set-uri: https://cognito-idp.us-east-1.amazonaws.com/us-east-1_8r9aHJxHT/.well-known/jwks.json
      client:
        clientId: reqk646491s71irk87m2bs027

