spring:
  datasource:
    url: jdbc:mysql://devlog.cwmrubevoikp.us-east-1.rds.amazonaws.com:3306/devlog
    username: admin
    password: devlogpassword
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  amazon:
    aws:
      accesskey: ASIATKFXOLMB6UOUCNOH
      secretkey: zt9aRYIWuIBev29xWE2l954nFrO30bvDKHGMwZDS
      sessiontoken: FwoGZXIvYXdzEHcaDGvNWWIU1PmQe19VpSLGAVzvlLjP4gpsLVURS26dvUwxj5ehh5WAzeM8WFEEi8JL3NPfqrvqCScaCM6yKmgqofZOozFSHVzleaeL/wSPlO/peWPblkbDtKkT9h4dDUc6XGlJp7LQqu3CCWrGn4pfcIoVL0yS2/zqskQ/04zDj67VP3OqwiOFiavWt/CxK/X5B2ULFaWauMkag0clH+MtrwzdQ1qvFXjF8Oj8+A3uh7UZPMktiRxAwsV2RrzzH2nLkbK9eux+7e2F+hGkGH9tn6aN2r9qYii0oKeqBjIt1Wtwymi73qSlSCELVINeUG/vvWgLWh7Va2IWG3PaFwi1JoNHpC0DeF5+Bzaz

      region: us-east-1  # e.g., us-east-1
      endpoint: https://dynamodb.us-east-1.amazonaws.com
      s3bucket-name: devlogresource
      s3Url: https://devlogresource.s3.amazonaws.com/
  security:
    oauth2:
      resource:
        userInfoUri: https://devlog.auth.us-east-1.amazoncognito.com/oauth2/userInfo
        tokenInfoUri: https://devlog.auth.us-east-1.amazoncognito.com/oauth2/token
        jwk:
          issuer-uri: https://cognito-idp.us-east-1.amazonaws.com/us-east-1_8r9aHJxHT
          key-set-uri: https://cognito-idp.us-east-1.amazonaws.com/us-east-1_8r9aHJxHT/.well-known/jwks.json
      client:
        clientId: reqk646491s71irk87m2bs027

