spring:
  datasource:
    url: jdbc:mysql://devlog.cwmrubevoikp.us-east-1.rds.amazonaws.com:3306/devlog
    username: admin
    password: devlogpassword
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  amazon:
    aws:
      accesskey: ASIATKFXOLMBYQJHDTOG
      secretkey: bj5Jk7u/h/SWyjRgO5HE7gdnOqpocvAZs+e8xdAY
      sessiontoken: FwoGZXIvYXdzEL7//////////wEaDLwcQoVi5PTVYO1DRSLGAcGwAbRjJfZdEA2JVlT3BPB+K4wvsmjDwgIu/zqRn7FSortliD/N/iGvHEpb/2nQ7B3BL1h9edwG6OGqJHCkElwyGOWUSpTHrvhPpLWRysOWudcEap1EoQEvP4V6KLCXnqArhmaS1EbkXTC73Ko16NZjvFo7eTg+RiOqHkXix3uWU5o0GOShGCInFkptIS6GLpIYMfk/sIJk8R5Gp4xeYvhmailD5ugOfV17OxhjtLROxu1T5QEhI/MpLTZvlPUf3aDeQ70uriisxP6pBjItPpXXi220QxnWq7+G9h02h+i/M1CI5/4X9+Ea58sJ0Tm6+ke1P9tLYvZtmJgY

      region: us-east-1  # e.g., us-east-1
      endpoint: https://dynamodb.us-east-1.amazonaws.com
      s3bucket-name: devlogresource
      s3Url: https://devlogresource.s3.amazonaws.com/
  security:
    oauth2:
      resource:
        userInfoUri: https://devlog.auth.us-east-1.amazoncognito.com/oauth2/userInfo
        tokenInfoUri: https://devlog.auth.us-east-1.amazoncognito.com/oauth2/token
        jwk:
          issuer-uri: https://cognito-idp.us-east-1.amazonaws.com/us-east-1_8r9aHJxHT
          key-set-uri: https://cognito-idp.us-east-1.amazonaws.com/us-east-1_8r9aHJxHT/.well-known/jwks.json
      client:
        clientId: reqk646491s71irk87m2bs027

